/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed": "#00174b",
              "surface-container": "#131b2e",
              "outline": "#434655",
              "inverse-surface": "#eaf1ff",
              "on-background": "#f8f9ff",
              "secondary-fixed-dim": "#4edea3",
              "surface-container-low": "#0b1326",
              "inverse-primary": "#004ac6",
              "primary-container": "#2563eb",
              "tertiary-fixed-dim": "#ffb95f",
              "on-tertiary-fixed": "#2a1700",
              "inverse-on-surface": "#0b1c30",
              "on-secondary-fixed": "#002113",
              "on-primary-fixed-variant": "#003ea8",
              "surface-container-lowest": "#060e20",
              "surface": "#0b1326",
              "surface-dim": "#0b1326",
              "surface-tint": "#2563eb",
              "secondary-container": "#005236",
              "error-container": "#93000a",
              "on-error-container": "#ffdad6",
              "on-error": "#ffffff",
              "on-secondary-fixed-variant": "#6ffbbe",
              "surface-container-highest": "#31394d",
              "secondary": "#4edea3",
              "on-surface-variant": "#c3c6d7",
              "on-secondary-container": "#6cf8bb",
              "surface-variant": "#31394d",
              "primary": "#3b82f6",
              "primary-fixed": "#dbe1ff",
              "on-surface": "#f8f9ff",
              "surface-bright": "#31394d",
              "on-tertiary-fixed-variant": "#ffddb8",
              "outline-variant": "#434655",
              "secondary-fixed": "#6ffbbe",
              "background": "#060e20",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#ffddb8",
              "tertiary-container": "#996100",
              "on-primary-container": "#ffffff",
              "surface-container-high": "#1c253d",
              "tertiary": "#ffb95f",
              "on-secondary": "#002113",
              "on-primary": "#ffffff",
              "on-tertiary-container": "#ffeedd",
              "error": "#ffb4ab",
              "primary-fixed-dim": "#b4c5ff"
      },
      "borderRadius": {
              "DEFAULT": "0.5rem",
              "lg": "0.75rem",
              "xl": "1rem",
              "full": "9999px"
      },
      "spacing": {
              "3xl": "64px",
              "margin-desktop": "32px",
              "margin-mobile": "16px",
              "md": "16px",
              "sm": "8px",
              "gutter": "24px",
              "xs": "4px",
              "base": "4px",
              "container-max": "1440px",
              "xl": "32px",
              "lg": "24px",
              "2xl": "48px"
      },
      "fontFamily": {
              "display-sm": ["Google Sans Flex", "sans-serif"],
              "title-md": ["Google Sans Flex", "sans-serif"],
              "headline-lg": ["Google Sans Flex", "sans-serif"],
              "label-md": ["Google Sans Flex", "sans-serif"],
              "mono-label": ["Google Sans Flex", "sans-serif"],
              "display-lg": ["Google Sans Flex", "sans-serif"],
              "headline-lg-mobile": ["Google Sans Flex", "sans-serif"],
              "body-lg": ["Google Sans Flex", "sans-serif"],
              "body-md": ["Google Sans Flex", "sans-serif"]
      },
      "fontSize": {
              "display-sm": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
              "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
              "mono-label": ["11px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-lg-mobile": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      },
      "animation": {
        'bounce-slow': 'bounce 3s infinite',
      }
    },
  },
  plugins: [],
};
